#! Template Language Syntax Test
#! This file demonstrates Clarion Template Language features
#TEMPLATE(TestTemplate, 'Test Template for Syntax Highlighting')
#HELP('TestHelp.chm')

#! Section definitions
#APPLICATION('Test Application')
  #! Generate application files
  #CREATE(%AppName & '.clw')
  PROGRAM
  #APPEND(%AppName & '.inc')
  #! Include necessary files
  #CLOSE(%AppName & '.clw')
#!

#! Procedure template with prompts
#PROCEDURE(TestProc, 'Test Procedure Template')
  #PROMPT('Procedure &Name:', @s30), %ProcName, REQ
  #PROMPT('&Description:', @s60), %ProcDesc
  #PROMPT('Enable &Logging', CHECK), %EnableLog, DEFAULT(%False)
  #BOXED('Options')
    #PROMPT('File to Process:', DROP('Customer|Orders|Products')), %ProcessFile
    #DISPLAY('Selected: ' & %ProcessFile)
  #ENDBOXED
  
  #! Control flow examples
  #IF(%EnableLog)
    #MESSAGE('Logging is enabled for ' & %ProcName)
  #ELSIF(%ProcessFile = 'Customer')
    #MESSAGE('Processing customer file')
  #ELSE
    #MESSAGE('No special processing')
  #ENDIF
  
  #! Case statement example
  #CASE(%ProcessFile)
  #OF('Customer')
    #SET(%FilePrefix, 'CUS')
    #SET(%KeyField, 'CustomerNumber')
  #OF('Orders')
    #SET(%FilePrefix, 'ORD')
    #SET(%KeyField, 'OrderNumber')
  #OROF('Products')
    #SET(%FilePrefix, 'PRD')
    #SET(%KeyField, 'ProductCode')
  #ENDCASE
  
  #! Loop example - iterate through files
  #FOR(%File)
    #IF(%FileType = 'MEMO' OR %FileType = 'ASCII')
      #! Generate code for file processing
      OPEN(%File)
      #INSERT(%ProcessFileGroup)
      CLOSE(%File)
    #ELSE
      #ERROR('Unsupported file type: ' & %FileType)
      #ABORT
    #ENDIF
  #ENDFOR
  
  #! Symbol management
  #DECLARE(%Counter)
  #EQUATE(%MaxRecords, 1000)
  #SET(%Counter, 0)
  
  #LOOP WHILE(%Counter < %MaxRecords)
    #SET(%Counter, %Counter + 1)
    #! Process record %Counter
  #ENDLOOP
  
  #! Target language code (Clarion)
  %ProcName PROCEDURE
    CODE
    MESSAGE('This is generated Clarion code')
    MESSAGE('Procedure: ' & %ProcName)
    !This is a Clarion comment in target code
    RETURN
  
  #! Embed point definition
  #EMBED(%BeforeProcess, 'Before Processing'), HIDE
  #EMBED(%AfterProcess, 'After Processing'), HIDE
#!

#! Reusable code group
#GROUP(%ProcessFileGroup)
  #! This group can be inserted anywhere
  IF ERRORCODE()
    MESSAGE('Error opening file: ' & %FileName)
    #IF(%EnableLog)
      ! Log the error
      LOG:File = %FileName
      LOG:Error = ERRORCODE()
      ADD(LogQueue)
    #ENDIF
  ELSE
    LOOP
      NEXT(%File)
      IF ERRORCODE() THEN BREAK.
      ! Process record here
    END
  END
#!

#! Code template
#CODE(AddLogging, 'Add Logging Code')
  #PROMPT('Log &Level:', DROP('Info|Warning|Error')), %LogLevel
  #PROMPT('Log &Message:', @s100), %LogMsg, REQ
  
  ! Generated logging code
  LOG:Level = '%LogLevel'
  LOG:Message = '%LogMsg'
  LOG:Time = CLOCK()
  LOG:Date = TODAY()
  ADD(LogQueue)
#!

#! Extension template
#EXTENSION(AutoSave, 'Automatic Save Extension')
  #PROMPT('Auto-save &Interval (seconds):', @n4), %SaveInterval, DEFAULT(60)
  
  #AT(%WindowOpening), PRIORITY(5000)
    ! Setup auto-save timer
    TIMER(EVENT:Timer, %SaveInterval * 100)
  #ENDAT
  
  #AT(%ControlEventHandling), WHERE(%ControlEvent = EVENT:Timer)
    ! Auto-save logic
    IF ~SELF.Response
      DO SaveRecord
    END
  #ENDAT
#!

#! Multi-valued symbol example
#DECLARE(%FieldList, MULTI)
#ADD(%FieldList, 'CustomerName')
#ADD(%FieldList, 'CustomerAddress')
#ADD(%FieldList, 'CustomerPhone')

#! Iterate through multi-valued symbol
#FOR(%FieldList)
  %FieldList STRING(100)
#ENDFOR

#! Conditional source generation
#QUERY(%GenerateExtraCode)
  ! This code is conditionally generated
  #IF(%EnableDebug)
    DEBUG('Extra debug code')
  #ENDIF
#RESUME(%GenerateExtraCode)
#IF(%SomeCondition)
  #RELEASE(%GenerateExtraCode)
#ENDIF

#! Built-in symbols demonstration
#MESSAGE('Application: ' & %Application)
#MESSAGE('Procedure: ' & %Procedure)
#MESSAGE('File count: ' & %FileCount)

#! Macro definition
#DEFINE(%GenerateHeader)
  !====================================
  ! Generated by: %ProcName
  ! Date: %Date
  !====================================
#!

#! Expand macro
#EXPAND(%GenerateHeader)
